services:
  qdr-labeling:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - qdr-labeling-data:/app/label-studio-data

volumes:
  qdr-labeling-data:
    external: true