version: '3.8'

services:
  qdr-labeling:
    build: .
    container_name: qdr-labeling-container
    volumes:
      - qdr-data:/app/data
    ports:
      - "5000:5000"
      - "8080:8080"

volumes:
  qdr-data:
