version: '3.8'

services:
  qdr-labeling:
    build:
      context: .
      dockerfile: dockerfile.linux
    container_name: qdr-labeling-container
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - qdr-labeling-data:/app/label-studio-data

volumes:
  qdr-labeling-data:
    external: true
